### ISSUE TITLE
Issue with option --organelle

### ISSUE THREAD

**Issue by loraine-gueguen** [NBISweden/EMBLmyGFF3#14]
```
Traceback (most recent call last):
  File "/opt/6.x/python-2.7.2/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/6.x/python-2.7.2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/projet/fr2424/sib/lgueguen/git/gmod/EMBLmyGFF3/EMBLmyGFF3/__main__.py", line 4, in <module>
    main()
  File "/projet/fr2424/sib/lgueguen/git/gmod/EMBLmyGFF3/EMBLmyGFF3/EMBLmyGFF3.py", line 1277, in main
    writer.set_organelle( args.organelle )
  File "/projet/fr2424/sib/lgueguen/git/gmod/EMBLmyGFF3/EMBLmyGFF3/EMBLmyGFF3.py", line 964, in set_organelle
    organelle = self._verify( self.organelle, "organelle")
AttributeError: 'EMBL' object has no attribute 'organelle'
```

**Comment by yjx1217** [comment]
Encountered the same issue when specifying the "-g mitochondria" option.

**Comment by Juke34** [comment]
@yjx1217 Thank you for your feedback. Inded there was a regressoin here.
You can use the code from the master branch for a working version

**Comment by yjx1217** [comment]
Hi @Juke34 ,

Many thanks for the quick fix!

Best,
Jia-Xing
