### ISSUE TITLE
Programme failed: ... KeyboardInterrupt Terminated

### ISSUE THREAD

**Issue by CristianRiccio** [NBISweden/EMBLmyGFF3#23]
Hi,

I've run EMBLmyGFF3 on a cluster in the following way:

`EMBLmyGFF3 c_elegans.PRJNA13758.WS263.annotations.gff3 c_elegans.PRJNA13758.WS263.genomic.fa --topology linear --molecule_type 'genomic DNA' --transl_table 1 --species 'Caenorhabditis elegans' --locus_tag CELE --project_id PRJNA13758 -o c_elegans.PRJNA13758.WS263.annotations.embl`

I have checked that I have Python 2.6, Biopython 1.67 and bcbio-gff 0.6.4. I can successfully pull out the help from EMBLmyGFF3.

I got the following output from my command above:

```
Traceback (most recent call last):
  File "/nfs/users/nfs_c/user/anaconda3/envs/python2env/bin/EMBLmyGFF3", line 11, in <module>
    load_entry_point('EMBLmyGFF3==1.2.3', 'console_scripts', 'EMBLmyGFF3')()
  File "/nfs/users/nfs_c/user/anaconda3/envs/python2env/lib/python2.7/site-packages/EMBLmyGFF3-1.2.3-py2.7.egg/EMBLmyGFF3/EMBLmyGFF3.py", line 1275, in main
    for record in GFF.parse(infile, base_dict=seq_dict):
  File "build/bdist.linux-x86_64/egg/BCBio/GFF/GFFParser.py", line 742, in parse
  File "build/bdist.linux-x86_64/egg/BCBio/GFF/GFFParser.py", line 322, in parse_in_parts
  File "build/bdist.linux-x86_64/egg/BCBio/GFF/GFFParser.py", line 343, in parse_simple
  File "build/bdist.linux-x86_64/egg/BCBio/GFF/GFFParser.py", line 637, in _gff_process
  File "build/bdist.linux-x86_64/egg/BCBio/GFF/GFFParser.py", line 667, in _lines_to_out_info
  File "build/bdist.linux-x86_64/egg/BCBio/GFF/GFFParser.py", line 189, in _gff_line_map
  File "build/bdist.linux-x86_64/egg/BCBio/GFF/GFFParser.py", line 89, in _split_keyvals
KeyboardInterrupt
Terminated
```
I submitted the command (in a .sh file) as a batch job with 20 MB memory on a GNU/Linux machine.

**Comment by Juke34** [comment]
It looks like a python version issue.
We have never tried Python 2.6, we recommend to use python 2.7.

**Comment by Juke34** [comment]
As we didn't get any feedback since a while, I assume you have found a solution. Consequently I close the issue. In case you disagree, feel free to answer here.
