### ISSUE TITLE
string index out of range (when sequence end by Ns)

### ISSUE THREAD

**Issue by Juke34** [NBISweden/EMBLmyGFF3#38]
Original question from @Iseez
Just one question more, when i was tryng to obtain the embl for a different species i encountered the following error:
```
Traceback (most recent call last):                                             ]
  File "/cm/shared/apps/emblmygff3/1.2.6/bin/EMBLmyGFF3", line 11, in <module>
    load_entry_point('EMBLmyGFF3==1.2.6', 'console_scripts', 'EMBLmyGFF3')()
  File "/cm/shared/apps/emblmygff3/1.2.6/lib/python2.7/site-packages/EMBLmyGFF3-1.2.6-py2.7.egg/EMBLmyGFF3/EMBLmyGFF3.py", line 1383, in main
    writer.write_all( outfile )
  File "/cm/shared/apps/emblmygff3/1.2.6/lib/python2.7/site-packages/EMBLmyGFF3-1.2.6-py2.7.egg/EMBLmyGFF3/EMBLmyGFF3.py", line 1179, in write_all
    self._add_mandatory()
  File "/cm/shared/apps/emblmygff3/1.2.6/lib/python2.7/site-packages/EMBLmyGFF3-1.2.6-py2.7.egg/EMBLmyGFF3/EMBLmyGFF3.py", line 195, in _add_mandatory
    if seq[end] == 'n' :
IndexError: string index out of range
```
Is the problem due to the files I'm using as input?

**Comment by Juke34** [comment]
Potentially yes. Do you have any other error / trace before this ? 
If you can send me your files I can have a look more in detail.

**Comment by Juke34** [comment]
Thank you for having reported this problem. This is indeed a bug.
Line 194 of EMBLmyGFF3.py 
`while end:`
has to be replaced by
`while end < len(seq):`

It will be fixed in a future release.
Until then, you can fix it yourself that way:

Uninstall EMBLmyGFF3:

`pip unistall EMBLmyGFF3`

clone the repo in a nice place:

```
mkdir ~/git
cd ~/git
git clone https://github.com/NBISweden/EMBLmyGFF3.git
cd EMBLmyGFF3
```
replace line 194 of  EMBLmyGFF3.py  as indicated before (here using the nano text editor but you can use what ever you want):
`nano EMBLmyGFF3/modules/feature.py`

install:

`python setup.py install`

or if you do not have administartive rights on your machine:

`python setup.py install --user`

--------------
Except this problem I can point 2 other problems:
1) The fasta headers are different of what is reported in  column 1 of the gff file. Be sure the annotation has been done using this fasta sequences. If it is the case fix the name they must be similar in both files otherwise EMBLmyGFF3 will not be able to match the features (gene,cds,etc) to the proper sequence. Currently no feature at all will be attached to the sequences. 
2) if you plan to submit the EMBL file created like that, you will have a rejection from ENA. Indeed they do not accept sequences that start or/and end with `N` (gaps). You have plenty of cases like that. This is also related to the current bug. If you shrink the N from extremities you will passthrough the current bug in EMBLmyGFF3 and do not encounter any rejection due to trailing Ns during ENA submission.
To do so first you must fix names between your gff and fasta files as indicated point 1 and then you can use the script `gff3_sp_clipN_seqExtremities_and_fixCoordinates.pl` from the [GAAS](https://github.com/NBISweden/GAAS) repository.
