### ISSUE TITLE
ZeroDivisionError (when --no_progress activated)

### ISSUE THREAD

**Issue by psur9757** [NBISweden/EMBLmyGFF3#40]
Hello 

I am trying to use EMBLmyGFF3 and I get the following error:
```
Traceback (most recent call last):
  File "/scratch/OSR/bin/EMBLmyGFF3/scripts/EMBLmyGFF3", line 11, in <module>
    load_entry_point('EMBLmyGFF3==1.2.6', 'console_scripts', 'EMBLmyGFF3')()
  File "/home/psur9757/.local/lib/python2.7/site-packages/EMBLmyGFF3/EMBLmyGFF3.py", line 1386, in main
    EMBL.print_progress(True)
  File "/home/psur9757/.local/lib/python2.7/site-packages/EMBLmyGFF3/EMBLmyGFF3.py", line 386, in print_progress
    progress = "[" + "="* int(78 * (float(EMBL.progress)/EMBL.total_features))
ZeroDivisionError: float division by zero
```

I checked the biopython and bcbgio-gff versions
> $ python --version
> Python 2.7.9
> $ python -c "import Bio; from BCBio import GFF; print 'biopython version: '+Bio.__version__; print 'bcbio-gff version: '+GFF.__version__"
> biopython version: 1.67
> bcbio-gff version: 0.6.4

My command:
```
samtools faidx $genome $scaffold -o $FASTAs/${scaffold}.fa
grep "^$scaffold" $gff > $GFFs/${scaffold}.gff3
$project/EMBLmyGFF3 --shame --no_progress --ra $AUTHOR --rg $REFERENCE_GROUP -i $LOCUS_TAG -p $PROJECT -m "$MOLECULE" -r $TABLE -t linear -s "$SPECIES" -x $TAXONOMY -o $EMBLs/${scaffold}.embl $GFFs/${scaffold}.gff3 $FASTAs/${scaffold}.fa
```

**Comment by Juke34** [comment]
Might be related to the of --no_progress parameter. Could you give a try without?
