### ISSUE TITLE
Bio.Alphabet has been removed from Biopython

### ISSUE THREAD

**Issue by metalichen** [NBISweden/EMBLmyGFF3#56]
Hi there,

I installed EMBLmyGFF3 via conda. When I try to run it, I get an error:

```
Traceback (most recent call last):
  File "/home/tagirdzh/miniconda/envs/EMBLmyGFF3/bin/EMBLmyGFF3", line 6, in <module>
    from EMBLmyGFF3 import main
  File "/home/tagirdzh/miniconda/envs/EMBLmyGFF3/lib/python3.8/site-packages/EMBLmyGFF3/__init__.py", line 3, in <module>
    from .EMBLmyGFF3 import *
  File "/home/tagirdzh/miniconda/envs/EMBLmyGFF3/lib/python3.8/site-packages/EMBLmyGFF3/EMBLmyGFF3.py", line 4, in <module>
    from .modules.feature import Feature
  File "/home/tagirdzh/miniconda/envs/EMBLmyGFF3/lib/python3.8/site-packages/EMBLmyGFF3/modules/feature.py", line 10, in <module>
    from Bio.Alphabet.IUPAC import *
  File "/home/tagirdzh/miniconda/envs/EMBLmyGFF3/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```

Thanks!

**Comment by metalichen** [comment]
I guess I should mention it: I run it in in Ubuntu 18.04.4, python 3.8.6

**Comment by Juke34** [comment]
I have updated the Conda recipe today. It does not work with Biopython >= 1.78
You should use the emblmygff3-2-py_1 package or downgrade biopython.

**Comment by metalichen** [comment]
Thanks!
