### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by hcheng78** [NBISweden/EMBLmyGFF3#58]
I've tried downloading the program with all 3 options but I get errors everytime I try to download it or run it and I'm not sure what is wrong. Is it because I have the updated version of python?

Traceback (most recent call last):
  File "/Users/chengh1/miniconda3/bin/EMBLmyGFF3", line 33, in <module>
    sys.exit(load_entry_point('EMBLmyGFF3==2', 'console_scripts', 'EMBLmyGFF3')())
  File "/Users/chengh1/miniconda3/bin/EMBLmyGFF3", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/chengh1/miniconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/chengh1/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/EMBLmyGFF3-2-py3.8.egg/EMBLmyGFF3/__init__.py", line 3, in <module>
    from .EMBLmyGFF3 import *
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/EMBLmyGFF3-2-py3.8.egg/EMBLmyGFF3/EMBLmyGFF3.py", line 4, in <module>
    from .modules.feature import Feature
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/EMBLmyGFF3-2-py3.8.egg/EMBLmyGFF3/modules/feature.py", line 8, in <module>
    from Bio.Seq import Seq
ModuleNotFoundError: No module named 'Bio'

**Comment by Juke34** [comment]
Which Biopython do you use? You must use version <=1.77
I have made some fix in `speed` branch for this, but I'm waiting feedback before to merge

**Comment by hcheng78** [comment]
I have 1.78 installed through conda. 
Will the update allow this version or do I have to install 1.77 instead?

**Comment by Juke34** [comment]
The new version will constraint to install v1.77 and not later version. So do the change yourself in your conda env and it should work. It would be easier.

**Comment by hcheng78** [comment]
I'm still getting this error when trying to download through conda.

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                               

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

**Comment by Juke34** [comment]
Then it is better to install the version from the `speed` branch. Let me know if you do not know how to proceed

**Comment by hcheng78** [comment]
No, I don't.

**Comment by Juke34** [comment]
Give me feedback if the speed branch is working fine. (If you do not encounter any problem), then I would merge to the master

**Comment by hcheng78** [comment]
I finally got it installed but once I tried to run it I get this error. I provided it a gff and fa file in that order. 


    #############################################################################
    # EMBLmyGFF3 v2                                                             #
    # NBIS - National Bioinformatics Infrastructure Sweden                      #
    # Authors: Martin Norling, Niclas Jareborg, Jacques Dainat                  #
    # Please visit https://github.com/NBISweden/EMBLmyGFF3 for more information #
    #############################################################################

Traceback (most recent call last):
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", line 42, in __init__
    self.stream = open(source, "r" + mode)
TypeError: expected str, bytes or os.PathLike object, not FakeHandle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengh1/miniconda3/bin/EMBLmyGFF3", line 33, in <module>
    sys.exit(load_entry_point('EMBLmyGFF3==2', 'console_scripts', 'EMBLmyGFF3')())
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/EMBLmyGFF3-2-py3.8.egg/EMBLmyGFF3/EMBLmyGFF3.py", line 1346, in main
    for record in GFF.parse(infile, base_dict=seq_dict):
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/BCBio/GFF/GFFParser.py", line 745, in parse
    for rec in parser.parse_in_parts(gff_files, base_dict, limit_info,
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/BCBio/GFF/GFFParser.py", line 322, in parse_in_parts
    for results in self.parse_simple(gff_files, limit_info, target_lines):
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/BCBio/GFF/GFFParser.py", line 343, in parse_simple
    for results in self._gff_process(gff_files, limit_info, target_lines):
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/BCBio/GFF/GFFParser.py", line 637, in _gff_process
    for out in self._lines_to_out_info(line_gen, limit_info, target_lines):
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/BCBio/GFF/GFFParser.py", line 699, in _lines_to_out_info
    fasta_recs = self._parse_fasta(FakeHandle(line_iter))
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/BCBio/GFF/GFFParser.py", line 560, in _parse_fasta
    return list(SeqIO.parse(in_handle, "fasta"))
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/Bio/SeqIO/__init__.py", line 627, in parse
    i = iterator_generator(handle)
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/Bio/SeqIO/FastaIO.py", line 181, in __init__
    super().__init__(source, alphabet=alphabet, mode="t", fmt="Fasta")
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", line 46, in __init__
    if source.read(0) != "":
TypeError: read() takes 1 positional argument but 2 were given

**Comment by Juke34** [comment]
could you try in python 3.7?

**Comment by Juke34** [comment]
And can you share  your command?

**Comment by hcheng78** [comment]
This is what I typed in for the command.
I'm not sure how to switch over to python3.7.

chengh1$ EMBLmyGFF3 chr1.gff3 chr1.fasta > results.embl

    #############################################################################
    # EMBLmyGFF3 v2                                                             #
    # NBIS - National Bioinformatics Infrastructure Sweden                      #
    # Authors: Martin Norling, Niclas Jareborg, Jacques Dainat                  #
    # Please visit https://github.com/NBISweden/EMBLmyGFF3 for more information #
    #############################################################################

Traceback (most recent call last):
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", line 42, in __init__
    self.stream = open(source, "r" + mode)
TypeError: expected str, bytes or os.PathLike object, not FakeHandle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengh1/miniconda3/bin/EMBLmyGFF3", line 33, in <module>
    sys.exit(load_entry_point('EMBLmyGFF3==2', 'console_scripts', 'EMBLmyGFF3')())
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/EMBLmyGFF3-2-py3.8.egg/EMBLmyGFF3/EMBLmyGFF3.py", line 1346, in main
    for record in GFF.parse(infile, base_dict=seq_dict):
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/BCBio/GFF/GFFParser.py", line 745, in parse
    for rec in parser.parse_in_parts(gff_files, base_dict, limit_info,
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/BCBio/GFF/GFFParser.py", line 322, in parse_in_parts
    for results in self.parse_simple(gff_files, limit_info, target_lines):
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/BCBio/GFF/GFFParser.py", line 343, in parse_simple
    for results in self._gff_process(gff_files, limit_info, target_lines):
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/BCBio/GFF/GFFParser.py", line 637, in _gff_process
    for out in self._lines_to_out_info(line_gen, limit_info, target_lines):
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/BCBio/GFF/GFFParser.py", line 699, in _lines_to_out_info
    fasta_recs = self._parse_fasta(FakeHandle(line_iter))
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/BCBio/GFF/GFFParser.py", line 560, in _parse_fasta
    return list(SeqIO.parse(in_handle, "fasta"))
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/Bio/SeqIO/__init__.py", line 627, in parse
    i = iterator_generator(handle)
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/Bio/SeqIO/FastaIO.py", line 181, in __init__
    super().__init__(source, alphabet=alphabet, mode="t", fmt="Fasta")
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", line 46, in __init__
    if source.read(0) != "":
TypeError: read() takes 1 positional argument but 2 were given

**Comment by Juke34** [comment]
Could you try `-o results.embl` instead of `> results.embl`

**Comment by hcheng78** [comment]
I'm getting the same error message.

chengh1$ EMBLmyGFF3 chr1.gff3 chr1.fasta > results.embl

    #############################################################################
    # EMBLmyGFF3 v2                                                             #
    # NBIS - National Bioinformatics Infrastructure Sweden                      #
    # Authors: Martin Norling, Niclas Jareborg, Jacques Dainat                  #
    # Please visit https://github.com/NBISweden/EMBLmyGFF3 for more information #
    #############################################################################

Traceback (most recent call last):
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", line 42, in __init__
    self.stream = open(source, "r" + mode)
TypeError: expected str, bytes or os.PathLike object, not FakeHandle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengh1/miniconda3/bin/EMBLmyGFF3", line 33, in <module>
    sys.exit(load_entry_point('EMBLmyGFF3==2', 'console_scripts', 'EMBLmyGFF3')())
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/EMBLmyGFF3-2-py3.8.egg/EMBLmyGFF3/EMBLmyGFF3.py", line 1346, in main
    for record in GFF.parse(infile, base_dict=seq_dict):
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/BCBio/GFF/GFFParser.py", line 745, in parse
    for rec in parser.parse_in_parts(gff_files, base_dict, limit_info,
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/BCBio/GFF/GFFParser.py", line 322, in parse_in_parts
    for results in self.parse_simple(gff_files, limit_info, target_lines):
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/BCBio/GFF/GFFParser.py", line 343, in parse_simple
    for results in self._gff_process(gff_files, limit_info, target_lines):
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/BCBio/GFF/GFFParser.py", line 637, in _gff_process
    for out in self._lines_to_out_info(line_gen, limit_info, target_lines):
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/BCBio/GFF/GFFParser.py", line 699, in _lines_to_out_info
    fasta_recs = self._parse_fasta(FakeHandle(line_iter))
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/BCBio/GFF/GFFParser.py", line 560, in _parse_fasta
    return list(SeqIO.parse(in_handle, "fasta"))
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/Bio/SeqIO/__init__.py", line 627, in parse
    i = iterator_generator(handle)
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/Bio/SeqIO/FastaIO.py", line 181, in __init__
    super().__init__(source, alphabet=alphabet, mode="t", fmt="Fasta")
  File "/Users/chengh1/miniconda3/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", line 46, in __init__
    if source.read(0) != "":
TypeError: read() takes 1 positional argument but 2 were given

**Comment by Juke34** [comment]
I didn't pay attention you did not switch to python 3.7. I guess it can fix the problem. 
`conda install python=3.7`

**Comment by Juke34** [comment]
btw did you try the included test? `EMBLmyGFF3-maker-example` to be sure it is not related to the provided files

**Comment by hcheng78** [comment]
I'm getting a bunch of errors when I use the conda install python=3.7 command. 
But when I run the other one I get this. 

chengh1$ EMBLmyGFF3-maker-example
Running the following command: EMBLmyGFF3 --rg REFERENCE_GROUP -i MYLOCUSTAG -p 17285 -m "genomic DNA" -r 1 -t linear -s "Drosophila melanogaster" -x INV -o EMBLmyGFF3-maker-example.embl /Users/chengh1/miniconda3/lib/python3.8/site-packages/EMBLmyGFF3-2-py3.8.egg/examples/maker.gff3 /Users/chengh1/miniconda3/lib/python3.8/site-packages/EMBLmyGFF3-2-py3.8.egg/examples/maker.fa

    #############################################################################
    # EMBLmyGFF3 v2                                                             #
    # NBIS - National Bioinformatics Infrastructure Sweden                      #
    # Authors: Martin Norling, Niclas Jareborg, Jacques Dainat                  #
    # Please visit https://github.com/NBISweden/EMBLmyGFF3 for more information #
    #############################################################################

17:30:58 WARNING feature: Unknown qualifier '_AED' - skipped                   ]
17:30:58 WARNING feature: Unknown qualifier '_eAED' - skipped
17:30:58 WARNING feature: Unknown qualifier '_QI' - skipped
Conversion done

**Comment by Juke34** [comment]
Ok the test works. So the problem is either the command or the files you provide as input. Have you check the path and that they are in read? Are you sure there is data inside ?

**Comment by hcheng78** [comment]
I downloaded it with python3.7 and made use that I was in the same directory as my input files and made sure that they contained the correct information for the files, I redownloaded it from the source just to be sure and I still get this error. 

$ EMBLmyGFF3 chr2.gff3 chr2.fasta 

    #############################################################################
    # EMBLmyGFF3 v2                                                             #
    # NBIS - National Bioinformatics Infrastructure Sweden                      #
    # Authors: Martin Norling, Niclas Jareborg, Jacques Dainat                  #
    # Please visit https://github.com/NBISweden/EMBLmyGFF3 for more information #
    #############################################################################

Traceback (most recent call last):
  File "/home/whitehoi/.local/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 42, in __init__
    self.stream = open(source, "r" + mode)
TypeError: expected str, bytes or os.PathLike object, not FakeHandle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/whitehoi/.local/bin/EMBLmyGFF3", line 10, in <module>
    sys.exit(main())
  File "/home/whitehoi/.local/lib/python3.7/site-packages/EMBLmyGFF3/EMBLmyGFF3.py", line 1346, in main
    for record in GFF.parse(infile, base_dict=seq_dict):
  File "/home/whitehoi/.local/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 746, in parse
    target_lines):
  File "/home/whitehoi/.local/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 322, in parse_in_parts
    for results in self.parse_simple(gff_files, limit_info, target_lines):
  File "/home/whitehoi/.local/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 343, in parse_simple
    for results in self._gff_process(gff_files, limit_info, target_lines):
  File "/home/whitehoi/.local/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 637, in _gff_process
    for out in self._lines_to_out_info(line_gen, limit_info, target_lines):
  File "/home/whitehoi/.local/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 699, in _lines_to_out_info
    fasta_recs = self._parse_fasta(FakeHandle(line_iter))
  File "/home/whitehoi/.local/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 560, in _parse_fasta
    return list(SeqIO.parse(in_handle, "fasta"))
  File "/home/whitehoi/.local/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 627, in parse
    i = iterator_generator(handle)
  File "/home/whitehoi/.local/lib/python3.7/site-packages/Bio/SeqIO/FastaIO.py", line 181, in __init__
    super().__init__(source, alphabet=alphabet, mode="t", fmt="Fasta")
  File "/home/whitehoi/.local/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 46, in __init__
    if source.read(0) != "":
TypeError: read() takes 1 positional argument but 2 were given

**Comment by Juke34** [comment]
Again try the test to see if it is suppose to work: `EMBLmyGFF3-maker-example`
Then show me your folder `ls -l`

**Comment by Juke34** [comment]
I guess one of your file is not properly formated or empty

**Comment by hcheng78** [comment]
$ EMBLmyGFF3-maker-example
Running the following command: EMBLmyGFF3 --rg REFERENCE_GROUP -i MYLOCUSTAG -p 17285 -m "genomic DNA" -r 1 -t linear -s "Drosophila melanogaster" -x INV -o EMBLmyGFF3-maker-example.embl /home/whitehoi/.local/lib/python3.7/site-packages/examples/maker.gff3 /home/whitehoi/.local/lib/python3.7/site-packages/examples/maker.fa

    #############################################################################
    # EMBLmyGFF3 v2                                                             #
    # NBIS - National Bioinformatics Infrastructure Sweden                      #
    # Authors: Martin Norling, Niclas Jareborg, Jacques Dainat                  #
    # Please visit https://github.com/NBISweden/EMBLmyGFF3 for more information #
    #############################################################################

10:24:23 WARNING feature: Unknown qualifier '_AED' - skipped                   ]
10:24:23 WARNING feature: Unknown qualifier '_eAED' - skipped
10:24:23 WARNING feature: Unknown qualifier '_QI' - skipped
Conversion done                                                                 


$ ls -l
total 4482
-rwx------ 1 whitehoi whitehoi  826861 Oct 19 09:24 chr2.fasta
-rwx------ 1 whitehoi whitehoi 1633600 Mar  6  2020 chr2.gff3
-rwx------ 1 whitehoi whitehoi 2127177 Nov 19 10:24 EMBLmyGFF3-maker-example.embl

**Comment by hcheng78** [comment]
The files I downloaded were the ones from EMBOSS for the yeast genome.

**Comment by Juke34** [comment]
Test still working so probably something with the file. Could you give me a link to the files I will give a try

**Comment by hcheng78** [comment]
https://www.ncbi.nlm.nih.gov/nuccore/BK006935

Then for the fast file, I just used the standard s288c genome.

**Comment by Juke34** [comment]
I do not see any gff file at this address

**Comment by hcheng78** [comment]
Yes sorry, I did it manually above the title there is a thing that says "Send to: " and I choose "Destination" then changed the "Format" to "GFF3"
[chr1.gff.txt](https://github.com/NBISweden/EMBLmyGFF3/files/5568921/chr1.gff.txt)

**Comment by Juke34** [comment]
Could you give me the link to the Fasta to be sure I use the same?
