### ISSUE TITLE
TypeError: read() takes 1 positional argument but 2 were given?

### ISSUE THREAD

**Issue by VibrantStarling** [NBISweden/EMBLmyGFF3#66]
Hello, 

I'm getting this error when I try to run EMBLmyGFF3 when trying to convert a PROKKA gff output into an embl file. Any idea what might be causing it?

I'm working on a linux server in a conda environment with python 3.6 installed. 

''''
EMBLmyGFF3 thing/thing.gff ../thing.fna --topology circular --molecule_type "genomic DNA" --transl_table 11 --species "insert name here" --locus_tag THING --project_id PRJXXXXX --author "Davison H.R., Pilgrim J., Siozios S., Hurst G.D.D." --rt "thing annotated with PROKKA"  -o thing-embl-test.embl

    #############################################################################
    # EMBLmyGFF3 v2.1                                                           #
    # NBIS - National Bioinformatics Infrastructure Sweden                      #
    # Authors: Martin Norling, Niclas Jareborg, Jacques Dainat                  #
    # Please visit https://github.com/NBISweden/EMBLmyGFF3 for more information #
    #############################################################################

Traceback (most recent call last):
  File "/pub28/helend/.local/lib/python3.6/site-packages/Bio/SeqIO/Interfaces.py", line 42, in __init__
    self.stream = open(source, "r" + mode)
TypeError: expected str, bytes or os.PathLike object, not FakeHandle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pub28/helend/.local/bin/EMBLmyGFF3", line 8, in <module>
    sys.exit(main())
  File "/pub28/helend/.local/lib/python3.6/site-packages/EMBLmyGFF3/EMBLmyGFF3.py", line 1357, in main
    for record in GFF.parse(infile, base_dict=seq_dict):
  File "/pub28/helend/.local/lib/python3.6/site-packages/BCBio/GFF/GFFParser.py", line 746, in parse
    target_lines):
  File "/pub28/helend/.local/lib/python3.6/site-packages/BCBio/GFF/GFFParser.py", line 322, in parse_in_parts
    for results in self.parse_simple(gff_files, limit_info, target_lines):
  File "/pub28/helend/.local/lib/python3.6/site-packages/BCBio/GFF/GFFParser.py", line 343, in parse_simple
    for results in self._gff_process(gff_files, limit_info, target_lines):
  File "/pub28/helend/.local/lib/python3.6/site-packages/BCBio/GFF/GFFParser.py", line 637, in _gff_process
    for out in self._lines_to_out_info(line_gen, limit_info, target_lines):
  File "/pub28/helend/.local/lib/python3.6/site-packages/BCBio/GFF/GFFParser.py", line 699, in _lines_to_out_info
    fasta_recs = self._parse_fasta(FakeHandle(line_iter))
  File "/pub28/helend/.local/lib/python3.6/site-packages/BCBio/GFF/GFFParser.py", line 560, in _parse_fasta
    return list(SeqIO.parse(in_handle, "fasta"))
  File "/pub28/helend/.local/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 627, in parse
    i = iterator_generator(handle)
  File "/pub28/helend/.local/lib/python3.6/site-packages/Bio/SeqIO/FastaIO.py", line 181, in __init__
    super().__init__(source, alphabet=alphabet, mode="t", fmt="Fasta")
  File "/pub28/helend/.local/lib/python3.6/site-packages/Bio/SeqIO/Interfaces.py", line 46, in __init__
    if source.read(0) != "":
TypeError: read() takes 1 positional argument but 2 were given

''''

**Comment by Juke34** [comment]
Interesting, try to use the absolut path instead of "thing/thing.gff ../thing.fn" or copy/link those files locally and run with "EMBLmyGFF3 thing.gff thing.fna etc..."

**Comment by VibrantStarling** [comment]
Tried both ways, same result I'm afraid

**Comment by Juke34** [comment]
I found similar issue here: https://github.com/SegataLab/PanPhlAn_pangenome_exporter/issues/1
Could you check the version of biopython abd BCBio GFF in your environment?
You will have to modify the version of one of them.
