### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by magbphp** [NBISweden/EMBLmyGFF3#72]
Dear NBISweden,
I am facing some issues when --translate is added to the command line.  I am annotating a bacteriophage genome with the translation table 11 that allows 3 start codons. I have checked randomly my ORF coordinates and they all start with a proper start codon for this table and end with a proper stop codon.

The error message generated in R studio I am using. There are some tRNA is the GFF3.

With regards,

Nicolas GINET 

Traceback (most recent call last):                                             ]
  File "/Users/Nico/miniconda3/envs/emblmygff3/bin/EMBLmyGFF3", line 10, in <module>
    sys.exit(main())
  File "/Users/Nico/miniconda3/envs/emblmygff3/lib/python3.7/site-packages/EMBLmyGFF3/EMBLmyGFF3.py", line 1516, in main
    writer.write_all( outfile )
  File "/Users/Nico/miniconda3/envs/emblmygff3/lib/python3.7/site-packages/EMBLmyGFF3/EMBLmyGFF3.py", line 1221, in write_all
    out.write( self.FT() ) # FT - feature table data         (>=2 per entry)
  File "/Users/Nico/miniconda3/envs/emblmygff3/lib/python3.7/site-packages/EMBLmyGFF3/EMBLmyGFF3.py", line 767, in FT
    output += str(f)
  File "/Users/Nico/miniconda3/envs/emblmygff3/lib/python3.7/site-packages/EMBLmyGFF3/modules/feature.py", line 152, in __repr__
    output = self._feature_as_EMBL(self.no_wrap_qualifier) if self.type not in self.remove else ""
  File "/Users/Nico/miniconda3/envs/emblmygff3/lib/python3.7/site-packages/EMBLmyGFF3/modules/feature.py", line 201, in _feature_as_EMBL
    self.qualifiers["translation"].set_value(self.translation())
  File "/Users/Nico/miniconda3/envs/emblmygff3/lib/python3.7/site-packages/EMBLmyGFF3/modules/feature.py", line 550, in translation
    phase = int(self.qualifiers.get('codon_start').value[0]) - 1
IndexError: list index out of range

**Comment by Juke34** [comment]
Are you sure you use the correct coordinate system? How this gff has been generated?

**Comment by Juke34** [comment]
Any update from your side? Could you share the data?
