### ISSUE TITLE
Reporting the line number of the problematic input GFF3 files when parsing error is triggered

### ISSUE THREAD

**Issue by yjx1217** [NBISweden/EMBLmyGFF3#75]
Dear developers,

I am using EMBLmyGFF3 to convert my GFF3 files to EMBL files. It works greatly for most of my files but occasionally will enter the following error message: 

```
Traceback (most recent call last):
  File "/public/shared/tools/conda_emblmygff3_env/bin/EMBLmyGFF3", line 10, in <module>
    sys.exit(main())
  File "/public/shared/tools/conda_emblmygff3_env/lib/python3.8/site-packages/EMBLmyGFF3/EMBLmyGFF3.py", line 1516, in main
    writer.write_all( outfile )
  File "/public/shared/tools/conda_emblmygff3_env/lib/python3.8/site-packages/EMBLmyGFF3/EMBLmyGFF3.py", line 1221, in write_all
    out.write( self.FT() ) # FT - feature table data         (>=2 per entry)
  File "/public/shared/tools/conda_emblmygff3_env/lib/python3.8/site-packages/EMBLmyGFF3/EMBLmyGFF3.py", line 767, in FT
    output += str(f)
  File "/public/shared/tools/conda_emblmygff3_env/lib/python3.8/site-packages/EMBLmyGFF3/modules/feature.py", line 183, in __repr__
    output += feature_l3._feature_as_EMBL(self.no_wrap_qualifier) if feature_l3.type not in feature_l3.remove else ""
  File "/public/shared/tools/conda_emblmygff3_env/lib/python3.8/site-packages/EMBLmyGFF3/modules/feature.py", line 201, in _feature_as_EMBL
    self.qualifiers["translation"].set_value(self.translation())
  File "/public/shared/tools/conda_emblmygff3_env/lib/python3.8/site-packages/EMBLmyGFF3/modules/feature.py", line 550, in translation
    phase = int(self.qualifiers.get('codon_start').value[0]) - 1
IndexError: list index out of range
```
I was wondering if the developer could let EMBLmyGFF3 to also report the line number of the input GFF3 file whenever such kind  errors were triggered so that I can locate the error source much more easily. 

Thanks in advance!

Best,
Jia-Xing

**Comment by Juke34** [comment]
There is a phase problem. 
You can check your files:
```
awk '{if($3 == "CDS" && ($8 != 0 && $8 != 1 && $8 != 2)) print $8}' file
```

It must be 0,1 or 2 (only for CDS). 
I will update the code to throw a proper warning and set it to 0 by default.

**Comment by yjx1217** [comment]
Ha, I see! Many thanks for the help! :-)

Best,
Jia-Xing
